import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { motion } from "framer-motion";
import toast from "react-hot-toast";
import { AnimatedSection } from "@components/AnimatedSection";
import { StatsPanel } from "@components/StatsPanel";
import { IconBadge } from "@components/IconBadge";
import { PageLayout } from "@layouts/PageLayout";
import { downloadLink, partsContent } from "../data/content";
import { getProcessIcon } from "@components/ProcessIcon";
const fadeIn = {
    hidden: { opacity: 0, y: 32 },
    visible: { opacity: 1, y: 0 }
};
export const PartsManufacturingPage = () => {
    const handleSubmit = (event) => {
        event.preventDefault();
        toast.success("Užklausa išsiųsta. Susisieksime artimiausiu metu.");
        event.currentTarget.reset();
    };
    return (_jsxs(PageLayout, { downloadLabel: downloadLink.label, downloadHref: downloadLink.href, children: [_jsxs("section", { id: partsContent.hero.id, className: "hero-section parts-hero", children: [_jsx("div", { className: "hero-media", style: { backgroundImage: `url(${partsContent.hero.image})` } }), _jsxs("div", { className: "container hero-content parts-hero-content", children: [_jsx(motion.h1, { initial: fadeIn.hidden, animate: fadeIn.visible, transition: { duration: 0.6 }, children: partsContent.hero.title }), _jsx(motion.p, { className: "hero-lead", initial: fadeIn.hidden, animate: fadeIn.visible, transition: { duration: 0.6, delay: 0.1 }, children: partsContent.hero.description }), _jsx("div", { className: "hero-cta", children: partsContent.hero.actions.map((action) => {
                                    if (action.href) {
                                        return (_jsx("a", { className: `btn btn-${action.variant}`, href: action.href, download: action.variant === "primary", children: action.label }, action.label));
                                    }
                                    return (_jsx("button", { className: `btn btn-${action.variant}`, onClick: () => {
                                            if (!action.targetId)
                                                return;
                                            const section = document.getElementById(action.targetId);
                                            section?.scrollIntoView({ behavior: "smooth", block: "start" });
                                        }, children: action.label }, action.label));
                                }) }), _jsx(StatsPanel, { stats: partsContent.hero.stats })] })] }), _jsxs(AnimatedSection, { id: "kompetencijos", className: "section parts-highlights", children: [_jsxs("header", { className: "section-header", children: [_jsx("h2", { children: "Kod\u0117l partneriai renkasi mus" }), _jsx("p", { children: "Tiksl\u016Bs terminai, atsekamumas ir paj\u0117gumai padeda tapti j\u016Bs\u0173 tiekimo grandin\u0117s dalimi." })] }), _jsx("div", { className: "parts-highlight-grid", children: partsContent.highlights.map((item) => (_jsxs("article", { className: "parts-highlight-card", children: [_jsx("h3", { children: item.title }), _jsx("p", { children: item.description })] }, item.title))) })] }), _jsxs(AnimatedSection, { id: "paslaugos", className: "section parts-capabilities", children: [_jsxs("header", { className: "section-header", children: [_jsx("h2", { children: "Gamybos paj\u0117gumai" }), _jsx("p", { children: "Automatizuotos linijos, robotizuotas da\u017Eymas ir sertifikuotos med\u017Eiagos \u2013 kiekvienai partijai." })] }), _jsx("div", { className: "parts-capability-grid", children: partsContent.services.map((service) => (_jsxs("article", { className: "parts-capability-card", children: [_jsx("h3", { children: service.title }), _jsx("p", { children: service.description }), _jsx("ul", { children: service.points.map((point) => (_jsx("li", { children: point }, point))) })] }, service.title))) })] }), _jsxs(AnimatedSection, { id: "projektai", className: "section parts-showcase", children: [_jsxs("header", { className: "section-header", children: [_jsx("h2", { children: "\u012Egyvendinti projektai" }), _jsx("p", { children: "Nuo ma\u017E\u0173 serij\u0173 iki didelio masto u\u017Esakym\u0173 \u2013 gamyba prisitaiko prie j\u016Bs\u0173 grafiko." })] }), _jsx("div", { className: "parts-showcase-grid", children: partsContent.projects.map((project) => (_jsxs("article", { className: "parts-showcase-card", children: [_jsx("div", { className: "parts-showcase-media", style: { backgroundImage: `url(${project.image})` }, children: _jsx("span", { className: "sr-only", children: project.imageAlt }) }), _jsxs("div", { className: "parts-showcase-body", children: [_jsx("h3", { children: project.title }), _jsx("p", { children: project.description }), _jsx("div", { className: "parts-showcase-tags", children: project.metrics.map((metric) => (_jsx(IconBadge, { children: `${metric.label}: ${metric.value}` }, metric.label))) })] })] }, project.title))) })] }), _jsxs(AnimatedSection, { id: "procesas", className: "section section-timeline parts-process", children: [_jsxs("header", { className: "section-header", children: [_jsx("h2", { children: "Kaip dirbame" }), _jsx("p", { children: "Aptariame specifikacij\u0105, optimizuojame gamyb\u0105 ir pasir\u016Bpiname logistika iki pat montavimo vietos." })] }), _jsx("div", { className: "timeline", children: partsContent.process.map((step) => {
                            const Icon = getProcessIcon(step.icon);
                            return (_jsxs("div", { className: "timeline-step", children: [_jsx("div", { className: "timeline-icon", children: _jsx(Icon, { size: 28 }) }), _jsxs("div", { children: [_jsx("h3", { children: step.title }), _jsx("p", { children: step.description })] })] }, step.title));
                        }) })] }), _jsxs(AnimatedSection, { id: "garantijos", className: "section section-dark parts-assurance", children: [_jsx("header", { className: "section-header", children: _jsx("h2", { children: "K\u0105 u\u017Etikriname" }) }), _jsx("div", { className: "grid grid-3", children: partsContent.assurance.map((item) => (_jsxs("article", { className: "card", children: [_jsx("h3", { children: item.title }), _jsx("p", { children: item.description })] }, item.title))) })] }), _jsx(AnimatedSection, { id: partsContent.contact.id, className: "section parts-contact", children: _jsxs("div", { className: "parts-contact-wrapper", children: [_jsxs("div", { className: "parts-contact-card", children: [_jsxs("header", { children: [_jsx("h2", { children: partsContent.contact.title }), _jsx("p", { children: partsContent.contact.description })] }), _jsxs("div", { className: "contact-details", children: [_jsxs("div", { children: [_jsx("span", { className: "contact-label", children: "Kontaktinis asmuo" }), _jsx("p", { className: "contact-name", children: partsContent.contact.advisor.name }), _jsx("p", { className: "contact-role", children: partsContent.contact.advisor.role })] }), _jsxs("div", { className: "contact-actions", children: [_jsxs("a", { className: "btn btn-secondary", href: `tel:${partsContent.contact.advisor.phone}`, children: ["Skambinti ", partsContent.contact.advisor.phone] }), _jsx("a", { className: "btn btn-ghost", href: `mailto:${partsContent.contact.advisor.email}`, children: "Ra\u0161yti el. lai\u0161k\u0105" })] })] })] }), _jsxs("form", { className: "parts-contact-form", onSubmit: handleSubmit, children: [_jsxs("div", { className: "form-grid", children: [_jsxs("label", { className: "input-field", children: [_jsx("span", { children: "Vardas ir pavard\u0117 *" }), _jsx("input", { type: "text", name: "name", placeholder: "\u012Era\u0161ykite savo vard\u0105", required: true })] }), _jsxs("label", { className: "input-field", children: [_jsx("span", { children: "\u012Emon\u0117" }), _jsx("input", { type: "text", name: "company", placeholder: "\u012Emon\u0117s pavadinimas (neprivaloma)" })] }), _jsxs("label", { className: "input-field", children: [_jsx("span", { children: "El. pa\u0161tas *" }), _jsx("input", { type: "email", name: "email", placeholder: "vardas@imone.lt", required: true })] }), _jsxs("label", { className: "input-field", children: [_jsx("span", { children: "Telefonas *" }), _jsx("input", { type: "tel", name: "phone", placeholder: "+370 ...", required: true })] })] }), _jsxs("label", { className: "input-field", children: [_jsx("span", { children: "U\u017Eklausos detal\u0117s *" }), _jsx("textarea", { name: "message", placeholder: "Apra\u0161ykite detali\u0173 tip\u0105, kiekius ar termin\u0105", rows: 6, required: true })] }), _jsx("button", { type: "submit", className: "btn btn-primary", children: "Si\u0173sti u\u017Eklaus\u0105" })] })] }) })] }));
};
export default PartsManufacturingPage;
